version: '2.3'

services:
statping:
  container_name: statping
  image: adamboutcher/statping-ng
  restart: always
  ports:
    - 8080:8080
  volumes:
    - statping_data:/app
  links:
    - postgres
  depends_on:
    - postgres
  environment:
    DB_CONN: postgres
    DB_HOST: postgres
    DB_PORT: 5432
    DB_DATABASE: statping
    DB_USER: root
    DB_PASS: password123

postgres:
  container_name: postgres
  image: postgres:10.0-alpine
  ports:
    - 5432:5432
  volumes:
    - pg_data:/var/lib/postgresql/data/pg_data
  environment:
    POSTGRES_PASSWORD: password123
    POSTGRES_DB: statping
    POSTGRES_USER: root
    POSTGRES_PORT: 5432
    PGDATA: /var/lib/postgresql/data/pg_data
